name: Format

on: [ pull_request ]

jobs:

    formatting:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2 # v2 minimum required
            -   uses: axel-op/googlejavaformat-action@v3
                with:
                    args: "--set-exit-if-changed --aosp --skip-sorting-imports --skip-javadoc-formatting"
